//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_3x
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int PassWord { get; set; }
        public int CardNumber { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> CapitalMoney { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> CreditPrecent { get; set; }
        public int Type { get; set; }
        public byte OpenCard { get; set; }
        public People(string name, string lastName, int password, int cardNumber, int money, int capitalMoney, int credit, int creditPrecent, int type, byte openCard)
        {
            this.Name = name;
            this.LastName = lastName;
            this.PassWord = password;
            this.CardNumber = cardNumber;
            this.Money = money;
            this.CapitalMoney = capitalMoney;
            this.Credit = credit;
            this.CreditPrecent = creditPrecent;
            this.Type = type;
            this.OpenCard = openCard;

        }
        public People()
        {

        }
    }
}
